import { Poppins } from 'next/font/google';
import type { Metadata } from "next";
import Header from "./Header/header";
import Footer from "./Footer/footer";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <title>SalesForce</title>
      </head>
      <body className={poppins.className}>
        <Header/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
