import type { Metadata } from "next";
import Header from "./Header/header";
import Footer from "./Footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <title>SalesForce</title>
      </head>
      <body>
        <Header/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
